In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [9]:
data=pd.read_csv('final.csv')
print(data.head())

   temperature   humidity        ph    rainfall label
0    20.879744  82.002744  6.502985  202.935536  rice
1    21.770462  80.319644  7.038096  226.655537  rice
2    23.004459  82.320763  7.840207  263.964248  rice
3    26.491096  80.158363  6.980401  242.864034  rice
4    20.130175  81.604873  7.628473  262.717340  rice


In [10]:
data.shape

(3100, 5)

In [11]:
label= pd.get_dummies(data.label).iloc[: , 1:]
data= pd.concat([data,label],axis=1)
data.head()

temperature   humidity        ph    rainfall label  Black gram  Chickpea  \
0    20.879744  82.002744  6.502985  202.935536  rice           0         0   
1    21.770462  80.319644  7.038096  226.655537  rice           0         0   
2    23.004459  82.320763  7.840207  263.964248  rice           0         0   
3    26.491096  80.158363  6.980401  242.864034  rice           0         0   
4    20.130175  81.604873  7.628473  262.717340  rice           0         0   

   Coconut  Coffee  Cotton  ...  maize  mango  millet  muskmelon  orange  \
0        0       0       0  ...      0      0       0          0       0   
1        0       0       0  ...      0      0       0          0       0   
2        0       0       0  ...      0      0       0          0       0   
3        0       0       0  ...      0      0       0          0       0   
4        0       0       0  ...      0      0       0          0       0   

   papaya  pomegranate  rice  watermelon  wheat  
0       0            0     1           0      0  
1       0            0     1           0      0  
2       0            0     1           0      0  
3       0            0     1           0      0  
4       0            0     1           0      0  

[5 rows x 35 columns]

In [12]:
data.drop('label', axis=1,inplace=True)
data.head()

temperature   humidity        ph    rainfall  Black gram  Chickpea  \
0    20.879744  82.002744  6.502985  202.935536           0         0   
1    21.770462  80.319644  7.038096  226.655537           0         0   
2    23.004459  82.320763  7.840207  263.964248           0         0   
3    26.491096  80.158363  6.980401  242.864034           0         0   
4    20.130175  81.604873  7.628473  262.717340           0         0   

   Coconut  Coffee  Cotton  Ground Nut  ...  maize  mango  millet  muskmelon  \
0        0       0       0           0  ...      0      0       0          0   
1        0       0       0           0  ...      0      0       0          0   
2        0       0       0           0  ...      0      0       0          0   
3        0       0       0           0  ...      0      0       0          0   
4        0       0       0           0  ...      0      0       0          0   

   orange  papaya  pomegranate  rice  watermelon  wheat  
0       0       0            0     1           0      0  
1       0       0            0     1           0      0  
2       0       0            0     1           0      0  
3       0       0            0     1           0      0  
4       0       0            0     1           0      0  

[5 rows x 34 columns]

In [15]:
train=data.iloc[:, 0:4].values
test=data.iloc[: ,4:].values
test.shape

(3100, 30)

In [7]:
#Creating dummy variable for target i.e label
label= pd.get_dummies(data.label).iloc[: , 1:]
data= pd.concat([data,label],axis=1)
data.drop('label', axis=1,inplace=True)
print('The data present in one row of the dataset is')
print(data.head(1))
train=data.iloc[:, 0:4].values
test=data.iloc[: ,4:].values

AttributeError: 'DataFrame' object has no attribute 'label'

In [42]:
X_train,X_test,y_train,y_test=train_test_split(train,test,test_size=0.3,random_state=1)

In [43]:
x_train=list(X_train)
for i in range(len(x_train)):
    x_train[i]=[int(j) for j in X_train[i]]

In [44]:
x_test=list(X_test)
for i in range(len(x_test)):
    x_test[i]=[int(j) for j in X_test[i]]

In [27]:
Y_train=list(y_train)
for i in range(len(Y_train)):
    Y_train[i]=[int(j) for j in y_train[i]]

In [28]:
Y_test=list(y_test)
for i in range(len(Y_test)):
    Y_test[i]=[int(j) for j in y_test[i]]

In [30]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [45]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [25]:
x_test

array([[-0.47533833,  0.92593437,  0.17329561,  0.66985182],
       [ 0.33145414,  0.37541255, -0.99095042,  0.88517626],
       [ 0.33145414,  0.50245605,  0.17329561,  0.10078006],
       ...,
       [-0.60980374,  0.20602123,  0.17329561, -0.66823582],
       [ 0.73485038, -0.38684842,  0.17329561,  0.42376673],
       [-0.34087292, -0.85267457,  0.17329561,  1.02359912]])

In [52]:
from sklearn.tree import DecisionTreeRegressor
clf=DecisionTreeRegressor()

In [91]:
from sklearn.ensemble import RandomForestClassifier
algo=RandomForestClassifier(n_estimators=10,random_state=10)

In [92]:
algo.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=10, verbose=0,
                       warm_start=False)

In [81]:
pred=algo.predict(x_test)

In [93]:
algo.score(x_test,y_test)

0.889247311827957

In [83]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, pred))

Accuracy: 0.8946236559139785


In [53]:
clf.fit(x_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [32]:
clf.fit(X_train,y_train)
pred=clf.predict(X_test)

In [54]:
clf.score(x_test,y_test)

C:\Users\Navee\Anaconda3\lib\site-packages\sklearn\base.py:420: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


0.7702461060655961

In [55]:
from sklearn.metrics import accuracy_score
# Finding the accuracy of the model
a=accuracy_score(y_test,pred)
print("The accuracy of this model is: ", a*100)

The accuracy of this model is:  87.41935483870968


In [84]:
crops=['wheat','mungbean','Tea','millet','maize','lentil','jute','cofee','cotton','ground nut','peas','rubber','sugarcane','tobacco','kidney beans','moth beans','coconut','blackgram','adzuki beans','pigeon peas','chick peas','banana','grapes','apple','mango','muskmelon','orange','papaya','watermelon','pomegranate']
cr="rice"

In [45]:
X_test[0]

array([-0.41755393,  0.90722754,  0.64519133,  0.6724524 ])

In [85]:
count=0
for j in range(len(pred)):
    for i in range(0,30):
        if(pred[j][i]==1):
            c=crops[i]
            count=count+1
            break;
    if(count==0):
        print('The predicted crop is %s'%cr)
    else:
        print('The predicted crop is %s'%c)

The predicted crop is jute
The predicted crop is kidney beans
The predicted crop is kidney beans
The predicted crop is muskmelon
The predicted crop is papaya
The predicted crop is mungbean
The predicted crop is cofee
The predicted crop is maize
The predicted crop is moth beans
The predicted crop is tobacco
The predicted crop is adzuki beans
The predicted crop is apple
The predicted crop is jute
The predicted crop is mango
The predicted crop is muskmelon
The predicted crop is jute
The predicted crop is apple
The predicted crop is moth beans
The predicted crop is moth beans
The predicted crop is cofee
The predicted crop is papaya
The predicted crop is moth beans
The predicted crop is maize
The predicted crop is tobacco
The predicted crop is tobacco
The predicted crop is pomegranate
The predicted crop is watermelon
The predicted crop is wheat
The predicted crop is wheat
The predicted crop is apple
The predicted crop is orange
The predicted crop is millet
The predicted crop is grapes
The p

The predicted crop is orange
The predicted crop is apple
The predicted crop is ground nut
The predicted crop is tobacco
The predicted crop is apple
The predicted crop is banana
The predicted crop is mungbean
The predicted crop is pigeon peas
The predicted crop is pigeon peas
The predicted crop is pigeon peas
The predicted crop is millet
The predicted crop is rubber
The predicted crop is coconut
The predicted crop is cotton
The predicted crop is adzuki beans
The predicted crop is coconut
The predicted crop is adzuki beans
The predicted crop is mango
The predicted crop is millet
The predicted crop is peas
The predicted crop is moth beans
The predicted crop is grapes
The predicted crop is adzuki beans
The predicted crop is adzuki beans
The predicted crop is adzuki beans
The predicted crop is rubber
The predicted crop is peas
The predicted crop is pomegranate
The predicted crop is Tea
The predicted crop is jute
The predicted crop is jute
The predicted crop is mungbean
The predicted crop is

The predicted crop is muskmelon
The predicted crop is maize
The predicted crop is chick peas
The predicted crop is cotton
The predicted crop is coconut
The predicted crop is peas
The predicted crop is maize
The predicted crop is moth beans
The predicted crop is tobacco
The predicted crop is papaya
The predicted crop is papaya
The predicted crop is pomegranate
The predicted crop is Tea
The predicted crop is mango
The predicted crop is chick peas
The predicted crop is maize
The predicted crop is maize
The predicted crop is orange
The predicted crop is mango
The predicted crop is tobacco
The predicted crop is tobacco
The predicted crop is grapes
The predicted crop is lentil
The predicted crop is maize
The predicted crop is Tea
The predicted crop is cofee
The predicted crop is moth beans
The predicted crop is lentil
The predicted crop is cotton
The predicted crop is wheat
The predicted crop is wheat
The predicted crop is watermelon
The predicted crop is ground nut
The predicted crop is pea

In [89]:
x=[[17,14,7,52]]
x = sc.transform(x)
res=clf.predict(x)
res

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [90]:
count=0
for i in range(0,30):
        if(res[0][i]==1):
            c=crops[i]
            count=count+1
            break;
        i=i+1
if(count==0):
    print('The predicted crop is %s'%cr)
else:
    print('The predicted crop is %s'%c)

The predicted crop is rubber


In [53]:
pred

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [88]:
from sklearn.metrics import multilabel_confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report
results=multilabel_confusion_matrix(y_test,pred)
print('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(y_test, pred) )
print ('Report : ')
print(classification_report(y_test, pred))

Confusion Matrix :
[[[896   0]
  [ 10  24]]

 [[894   0]
  [  2  34]]

 [[895   2]
  [  4  29]]

 [[902   2]
  [  1  25]]

 [[898   0]
  [  3  29]]

 [[889  10]
  [  2  29]]

 [[890   8]
  [  1  31]]

 [[889   2]
  [  0  39]]

 [[897   3]
  [  0  30]]

 [[898   0]
  [  5  27]]

 [[894   0]
  [  0  36]]

 [[895   0]
  [  0  35]]

 [[899   1]
  [ 10  20]]

 [[903   1]
  [  1  25]]

 [[904   1]
  [  4  21]]

 [[902   1]
  [  1  26]]

 [[895   5]
  [  0  30]]

 [[901   3]
  [  6  20]]

 [[911   1]
  [  1  17]]

 [[903   2]
  [  0  25]]

 [[890   3]
  [ 12  25]]

 [[899   2]
  [  0  29]]

 [[900   0]
  [  0  30]]

 [[904   0]
  [  0  26]]

 [[893   3]
  [  5  29]]

 [[892   3]
  [  8  27]]

 [[902   7]
  [  6  15]]

 [[902   1]
  [  4  23]]

 [[907   0]
  [  0  23]]

 [[890   7]
  [ 12  21]]]
Accuracy Score : 0.8946236559139785
Report : 
              precision    recall  f1-score   support

           0       1.00      0.71      0.83        34
           1       1.00      0.94      0.97   

C:\Users\Navee\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels.
  'precision', 'predicted', average, warn_for)
C:\Users\Navee\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels.
  'recall', 'true', average, warn_for)
