In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split

In [5]:
df=pd.read_csv("datafile.csv")

In [6]:
df.head()

Crop           State  Cost of Cultivation (`/Hectare) A2+FL  \
0  ARHAR   Uttar Pradesh                                9794.05   
1  ARHAR       Karnataka                               10593.15   
2  ARHAR         Gujarat                               13468.82   
3  ARHAR  Andhra Pradesh                               17051.66   
4  ARHAR     Maharashtra                               17130.55   

   Cost of Cultivation (`/Hectare) C2  Cost of Production (`/Quintal) C2  \
0                            23076.74                            1941.55   
1                            16528.68                            2172.46   
2                            19551.90                            1898.30   
3                            24171.65                            3670.54   
4                            25270.26                            2775.80   

   Yield (Quintal/ Hectare)   
0                       9.83  
1                       7.47  
2                       9.59  
3                       6.42  
4                       8.72

In [7]:
X = df[["Cost of Cultivation (`/Hectare) A2+FL","Cost of Cultivation (`/Hectare) C2","Cost of Production (`/Quintal) C2"]]
y = df["Yield (Quintal/ Hectare) "]

In [8]:
#Let's try Linear Regression first
from sklearn.linear_model import LinearRegression
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
clf = LinearRegression()
clf.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
clf.score(X_train,y_train)

0.7628293244599896

In [10]:
clf.score(X_test,y_test)

0.6875049532214044

In [11]:
#Now let's see GradientBoostingRegressor
alg =  GradientBoostingRegressor()
# Fitting the model
alg.fit(X_train,y_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [31]:
alg.fit(X,y)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [12]:
alg.score(X_test,y_test)        #Better accuracy

0.960302136740247

In [13]:
alg.predict([[5000,10000,2500]])

array([5.91478715])

In [32]:
w=[5000,10000,2500]
w=[w]
w

[[5000, 10000, 2500]]

In [29]:
import pickle

In [30]:
pickle.dump(alg, open('mod.pkl','wb'))
model = pickle.load(open('mod.pkl','rb'))
model.predict(q)

array([5.91478715])

In [33]:
q=np.array(w)
q

array([[ 5000, 10000,  2500]])

In [34]:
alg.predict(q)

array([4.02738567])

In [17]:
str='5000'
i=int(str)
i

5000

In [2]:
#from flask import Flask, render_template, request

In [ ]:
'''
app=Flask(__name__)

@app.route('/')
@app.route('/index')
def index():
    return flask.render_template('C:\\Users\\Navee\\SIH\\ml\\templates\\index.html')
if __name__ == '__main__':
    from werkzeug.serving import run_simple
    run_simple('127.0.0.1', 5000, app)
'''